name: Ambiente Desenvolvimento

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    name: Compilação
    runs-on: ubuntu-latest
    
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Configurar o JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Compilação
      run: mvn -B compile --file pom.xml
  qa:
    name: Qualidade de Código
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Análise SonarCloud
        run: chmod a+x ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.host.url=https://sonarcloud.io/
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    
