name: Ambiente Desenvolvimento

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    name: Compilação
    runs-on: ubuntu-latest
    
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Configurar o JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Compilação
      run: mvn -B compile --file pom.xml
  qa:
    name: Qualidade de Código
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Adicionar permissão para mvnw
        run: chmod +x mvnw
      - name: Análise SonarCloud
        run: ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=lab-devops-project
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  automatized-tests:
    name: Testes automatizados
    runs-on: ubuntu-latest
    needs: qa
    
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Configura JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Testes Unitários
        run: mvn -B test --file pom.xml
  send-heroku-image:
    name: Enviar imagem para o Heroku
    runs-on: ubuntu-latest
    needs: automatized-tests
    
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Prepara ambiente Docker
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login no Heroku
        uses: docker/login-action@v2
        with:
          registry: registry.heroku.com
          username: ${{ secrets.HEROKU_EMAIL }}
          password: ${{ secrets.HEROKU_API_KEY }}
      - name: Criação e envio da imagem
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.heroku.com/hellodocker2/web:latest


    
    
